version: '3.3'
services:
  web:
    image: omerkenig/wog_omer:1.1.1
    volumes:
      -  ./score.txt:/WOG/score.txt
    restart: always
    environment:
      WORKDIR: WOG
    ports:
      - "8081:5000"
